# This is a basic workflow to help you get started with Actions

name: Unit Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  test:
      strategy:
        matrix:
          # Test on the latest go version
          go-version: [1.20.x]
          platform: [ubuntu-latest, macos-latest, windows-latest]
        
      runs-on: ${{ matrix.platform }}
      
      steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
      - name: Vet
        run: go vet ./...
